language: node_js
node_js: "12"
cache:
  - pip
  - npm
jobs:
  include:
    - stage: lint, test, build
      install: npm ci
      script: npm run lint
    - script: npm run test
      env: NODESCRAPE_SKIP_ENV_VALIDATION=true
    - script: npm run build
    - stage: deploy
      script:
        - npm run clean
        - npm run build
        - bash ./.ci/deploy.sh prod
      if: branch = master AND type = push
      install:
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
        - nvm install 12
        - nvm use 12
        - node --version
        - pip install awscli aws-sam-cli --upgrade
        - npm ci
      language: python
      python:
        - "3.7"
      env:
        # AWS
        - secure: "TaB/tcXf3mmjEFnZVw8xgVhnpdXVxw83AHVunS3GHFscr4ng3UWcWI+d8CnMpwqseqOPOCo3gHy4WSWNmc0J8DoIrA8AK6bZCDhiILgEZlasTzxxc/f+IDkTd/ZgZGeqeOwLfxR22Lp7X5Rga3KGJyhD8IkNkz/6Mzdl9PqaBa31zeXroh6QO5n/0bwVH6BvN1OpWI/UPvsC14LqQ/b27yECbE6Z5tsQwaxVOQuskhwsoFkZG8ZjFVfyIAFEdaFiCRHcZnNWnDwk8wL6NbnN9Sa0+HgOyFt9AWo2BJZhTh/p28AqFuKJuKo6n+dO8bAOOKaO3BqVMQj3LCky9N1NMJSDQ5aLqsw3TT6YvC+as7qjqJ4JafRKmL/d4nR6J7P9Y57A4A1uN/gDNbVvdGHumbor/D65Blx/25ivbMo1FA6i/por/dZtP3YKP9CYawKtIbXO9SHBRNJ8z894eYewrLhpHMYN4hFIpUwFvQ2vl2S+Rm9mO1j4LCaUg4/GF+4j6sqNUSdAd8rVZTulVrs8/aQmUg29mnA9F4RTyUEPVERBgJv/wEQ5FsRFpp57HOCNNzivOvde7uFqAKAg6OPmnvpeIGW12juT3P0TwbGbQfbP6LrUIhHG6gc4IpMOW4nzyYk9Mn6BfYJP+9GNU4RG61lizHoepvnCRs/7QETXDB8="
        - secure: "R/ysuu0bVZgSIhnqEE29E54JjFY11z13GSeFLks53ssFCUqRi4pJQ0EQA89pMUag6aqoODepF1EFdX39OER2TCg4bCRkublQH+Ssc/XsHNQAmOdDjbQT0OF1/rmOhtJ6Amx6ZnI4VwOtzPzR2qZoPjt7ZzaJNGsgMWQsGQ3nDgBhJhvjMP8vPHQ99dI2JlYGnpIE6imeM7XyfBt7pEzJvkuMGPW+l540y/ROANq5OpqmRvPxIQ2zJe4a3XP0hi8+DTINOagLj29ax3PfMxx151SKrvb3OrxauJXygzpF1tvOgBEUr4F+ZHAfF4E3N/VD1u7UA55PMZ76p/sQNiSa4/LGb2Obo3LLMBKliDQ56I72zo7uWL9OwVQcu//zfHEyYP81cuJ0t0cpSmaxiUCYNhSYngu+AaiorSBxxE71nxSOkYUkoCsg/FhCmpzTdyqrDkqh6xOkuIBlA+W1IbqOhBCKBUH8xAxiXL50NTRE9sar7q7shEiCE2vxSftJcWm965eyA4zgwUo1ikli3MFvj+Cll6n2zgkKxDBzyOP5AN9fiIsm4fVa7NdI/JkxYJcf1HR5/2p6OD2ymfrQcA805z4QupE+LABltwtUpNk4/z3z8gIlnkI1ezLJIQxTEobGR7JY9UbaWo/eIFH4w7w0LdFVLMGzFDsnMN3rLFaEUsE="
        - AWS_DEFAULT_REGION=ap-southeast-2
        # NewsAPI key
        - secure: "o6VA8iOVIePkMRB9Aj/n1JTErytGeWBuo1Oo+izsHI0cplbaqng8uPnfzXMwvVk5JE+ST/aZiIiGhV8zEnJJw9JtxwilLA+DtO+lMl7SorSrLG426UhozNP2laQ5CCoGpswXSTJdtQGlH5yjCu7FkFmRAZawOXUbhdy9TUOYPUb+Mmg6vdVt/Ho+BnILt0f2J0dt81U2SoqADSlTELDxIKBDRpPebpP+atIyR3AMUYOLdBF0mY18vqY2P/Ist+ueEr6xWdeytQsaFa5Ac1HqUuxLnJN54lNWNeQv3/odTDWrawq3lLLfugRmDS9O/OZpUVC7sGlXG8QWNu9O9QKgH8cb6ZZHUxkGKLR8v9rlrJqGtttY1M3Xgo7+XktCGSdlrbbtUBm4+EtXz3L/pszWbK+768O/55/ATXq1abnrnXxQ8seowNCh3BuTeTyP9VKqBUs/S88nJxmguixyFKjyJo4UM0It6/hWS0ZmSCL1n8q1qz8G/0Z9FjF0u93dN3BqScryMVIfD7pRDXbTO8Bl5wRXafMm+a16c3uhZN1nfwicsy95znY4NTTkDplPv38uKPwXoXu2w+VWqwm7GpBS6U8MQABlpmiBfQkSDBWyx0VJ8m31pDwZdan7OvIQd6Vj0wJyhI+lBMSfwL80uM63UUrPNaYBkgvsRdwGodsFfZo="
