AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    SAMified Nodescrape.

Parameters:
    NewsApiApikey:
        Type: String
        NoEcho: true
    NewsApiUrl:
        Type: String
        Default: "https://newsapi.org/v2"
        Description: The URL to NewsAPI.org.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 10
        Environment:
            Variables:
                LOCAL_DYNAMODB_ENDPOINT: "http://192.168.99.100:8000"
                NODESCRAPE_LOG_LEVEL: DEBUG
                NEWS_API_APIKEY: !Ref NewsApiApikey
                NEWS_API_URL: !Ref NewsApiUrl
    Api:
        Cors:
            AllowMethods: "'*'"
            AllowOrigin: "'*'"
            AllowHeaders: "'*'"

Resources:    
    GetNewsSourcesFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/
            Handler: lambda-handlers/get-news.getNews
            Runtime: nodejs12.x
            Timeout: 30
            Events:
                GetNewsSourcesApi:
                    Type: Api
                    Properties:
                        Path: /news-scores
                        Method: get
            Policies:
                - DynamoDBCrudPolicy:
                    TableName: !Ref NewsSourceTable

    PingFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/
            Handler: lambda-handlers/hello-world.helloWorld
            Runtime: nodejs12.x
            Timeout: 30
            Events:
                GetNewsSourcesApi:
                    Type: Api
                    Properties:
                        Path: /.ping
                        Method: get

    CalculateNeutralityFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/
            Handler: calculate-neutrality.handler
            Runtime: nodejs12.x
            Timeout: 120
            Events:
                CalculateNeutralityApi:
                    Type: Api
                    Properties:
                        Path: /calculate
                        Method: get
                CNScheduledEvent:
                    Type: Schedule
                    Properties:
                        Schedule: rate(1 day)
            Policies:
                - DynamoDBCrudPolicy:
                    TableName: !Ref NewsSourceTable                    

    NewsSourceTable:
        Type: AWS::DynamoDB::Table
        Properties:
            Fn::Transform:
              Name: AWS::Include
              Parameters:
                Location: ./config/dynamo-schemas/news-sources.schema.json

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/disruptions-count"

